import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { Appointment, PatientProfile, ScanRecord } from "@prisma/client";

type BuildAdmissionsPdfInput = {
  hospitalName: string;
  generatedBy: string;
  patient: PatientProfile;
  appointments: Appointment[];
  scans: ScanRecord[];
};

function wrapText(text: string, maxChars = 78) {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (candidate.length <= maxChars) {
      current = candidate;
    } else {
      if (current) lines.push(current);
      current = word;
    }
  }

  if (current) lines.push(current);
  return lines.length ? lines : ["—"];
}

export async function buildAdmissionsPdf(input: BuildAdmissionsPdfInput) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const boldFont = await pdf.embedFont(StandardFonts.HelveticaBold);
  const regularFont = await pdf.embedFont(StandardFonts.Helvetica);

  const { width, height } = page.getSize();
  const margin = 38;
  let y = height - 52;

  page.drawRectangle({
    x: 0,
    y: height - 130,
    width,
    height: 130,
    color: rgb(0.03, 0.12, 0.25)
  });

  page.drawText(input.hospitalName, {
    x: margin,
    y: height - 58,
    font: boldFont,
    size: 24,
    color: rgb(1, 1, 1)
  });

  page.drawText("Admissions and clinical handover summary", {
    x: margin,
    y: height - 84,
    font: regularFont,
    size: 12,
    color: rgb(0.75, 0.9, 1)
  });

  page.drawText(`Generated by: ${input.generatedBy}`, {
    x: width - 190,
    y: height - 60,
    font: regularFont,
    size: 10,
    color: rgb(1, 1, 1)
  });

  page.drawText(`Created: ${new Date().toLocaleString("en-ZA")}`, {
    x: width - 190,
    y: height - 76,
    font: regularFont,
    size: 10,
    color: rgb(0.83, 0.89, 0.97)
  });

  y = height - 150;

  const section = (title: string) => {
    page.drawRectangle({
      x: margin,
      y: y - 8,
      width: width - margin * 2,
      height: 24,
      color: rgb(0.92, 0.96, 1)
    });

    page.drawText(title, {
      x: margin + 10,
      y,
      font: boldFont,
      size: 11,
      color: rgb(0.07, 0.2, 0.38)
    });

    y -= 30;
  };

  const pair = (label: string, value: string) => {
    page.drawText(label, {
      x: margin,
      y,
      font: boldFont,
      size: 9.5,
      color: rgb(0.14, 0.16, 0.2)
    });

    page.drawText(value || "—", {
      x: margin + 148,
      y,
      font: regularFont,
      size: 9.5,
      color: rgb(0.22, 0.24, 0.28)
    });

    y -= 15;
  };

  const paragraph = (label: string, value: string) => {
    page.drawText(label, {
      x: margin,
      y,
      font: boldFont,
      size: 9.5,
      color: rgb(0.14, 0.16, 0.2)
    });

    y -= 13;

    for (const line of wrapText(value)) {
      page.drawText(line, {
        x: margin + 10,
        y,
        font: regularFont,
        size: 9.5,
        color: rgb(0.22, 0.24, 0.28)
      });
      y -= 13;
    }

    y -= 2;
  };

  section("Patient identity");
  pair("Facility file no.", input.patient.facilityFileNumber);
  pair("Full name", input.patient.fullName);
  pair("SA ID / passport", input.patient.saId || input.patient.passportNumber);
  pair("Citizenship", input.patient.citizenship);
  pair("DOB / gender", `${input.patient.dateOfBirth.toISOString().slice(0, 10)} · ${input.patient.gender}`);
  pair("Phone", input.patient.phone);
  pair("Email", input.patient.email);
  pair("Address", `${input.patient.address}, ${input.patient.city}, ${input.patient.province}, ${input.patient.postalCode}`);
  y -= 6;

  section("Administrative and contact details");
  pair("Language", input.patient.language);
  pair("Preferred contact", input.patient.preferredContactMethod);
  pair("Marital status", input.patient.maritalStatus);
  pair("Occupation", input.patient.occupation);
  pair("Employer", `${input.patient.employer} · ${input.patient.employerPhone}`);
  pair("Arrival mode", input.patient.arrivalMode);
  pair("Referral", `${input.patient.referralSource} · ${input.patient.referringDoctor}`);
  pair("Triage priority", input.patient.triagePriority);
  y -= 6;

  section("Medical aid and emergency contacts");
  pair("Medical aid", input.patient.medicalAidScheme);
  pair("Plan / tier", `${input.patient.medicalAidPlan} · ${input.patient.membershipTier}`);
  pair("Membership no.", input.patient.medicalAidNumber);
  pair("Principal member", `${input.patient.principalMemberName} (${input.patient.relationshipToPrincipalMember})`);
  pair("Principal member no.", input.patient.principalMemberNumber);
  pair("Next of kin", `${input.patient.nextOfKin} (${input.patient.nextOfKinRelation})`);
  pair("Next of kin phone", input.patient.nextOfKinPhone);
  pair("Guardian", `${input.patient.guardianName} · ${input.patient.guardianPhone}`);
  y -= 6;

  section("Clinical and consent summary");
  pair("Visit pathway", input.patient.visitPathway);
  pair("Blood group", input.patient.bloodType);
  pair("Interpreter required", input.patient.interpreterRequired ? "Yes" : "No");
  pair("Disability support", input.patient.disabilitySupport);
  pair("Pregnancy status", input.patient.pregnancyStatus);
  pair(
    "Consents",
    [
      input.patient.popiaConsent ? "POPIA" : "",
      input.patient.consentTreatment ? "Treatment" : "",
      input.patient.consentDataSharing ? "Data-sharing" : "",
      input.patient.consentBilling ? "Billing" : ""
    ]
      .filter(Boolean)
      .join(", ")
  );
  paragraph("Allergies", input.patient.allergies);
  paragraph("Current medication", input.patient.currentMedication);
  paragraph("Chronic conditions", input.patient.chronicConditions);

  if (y < 210) {
    const continuation = pdf.addPage([595, 842]);
    const cWidth = continuation.getSize().width;
    continuation.drawText(`${input.hospitalName} · Appointments and imaging`, {
      x: margin,
      y: 800,
      font: boldFont,
      size: 18,
      color: rgb(0.07, 0.2, 0.38)
    });
    y = 770;

    for (const appointment of input.appointments.slice(0, 8)) {
      continuation.drawText(
        `${appointment.type} · ${appointment.department} · ${appointment.status} · ${appointment.scheduledAt.toISOString().slice(0, 16).replace("T", " ")}`,
        {
          x: margin,
          y,
          font: regularFont,
          size: 10,
          color: rgb(0.2, 0.24, 0.28),
          maxWidth: cWidth - margin * 2
        }
      );
      y -= 18;
    }

    y -= 12;

    for (const scan of input.scans.slice(0, 8)) {
      continuation.drawText(
        `${scan.modality} · ${scan.title} · ${scan.department} · ${scan.takenAt.toISOString().slice(0, 16).replace("T", " ")}`,
        {
          x: margin,
          y,
          font: regularFont,
          size: 10,
          color: rgb(0.2, 0.24, 0.28),
          maxWidth: cWidth - margin * 2
        }
      );
      y -= 18;
    }
  } else {
    section("Appointments");
    for (const appointment of input.appointments.slice(0, 4)) {
      paragraph(
        `${appointment.type} · ${appointment.status}`,
        `${appointment.department} at ${appointment.location} with ${appointment.clinician} on ${appointment.scheduledAt.toISOString().slice(0, 16).replace("T", " ")}. ${appointment.notes || ""}`
      );
    }

    section("Imaging");
    for (const scan of input.scans.slice(0, 3)) {
      paragraph(
        `${scan.modality} · ${scan.title}`,
        `${scan.department} uploaded by ${scan.uploadedBy} on ${scan.takenAt.toISOString().slice(0, 16).replace("T", " ")}. ${scan.notes || ""}`
      );
    }
  }

  return pdf.save();
}
